package model.service;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;


import model.service.common.AppModule;

import model.view.SpOrderLearningCurveVOImpl;
import model.view.SpOrderSetupVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 22 11:57:49 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respApplId) {  
        
    //    System.out.println("====================  set session values    ================================");

    //       System.out.println(" orgId "+ orgId  + "  data type  "+ orgId.getClass().getName());
    //
           orgId = "340";
           userId = "5219";
        FacesContext fctx = FacesContext.getCurrentInstance();
        ExternalContext ectx = fctx.getExternalContext();
        HttpSession userSession = (HttpSession)ectx.getSession(false);

        if (orgId != null) {
            userSession.setAttribute("orgId", orgId);
        }

        if (userId != null) {
            userSession.setAttribute("userId", userId);
        }

        if (respId != null) {
            userSession.setAttribute("respId", respId);
        }

        if (respApplId != null) {
            userSession.setAttribute("respApplId", respApplId);
        }         
         
      }


    /**
     * Container's getter for SpOrderSetupVO1.
     * @return SpOrderSetupVO1
     */
    public SpOrderSetupVOImpl getSpOrderSetupVO1() {
        return (SpOrderSetupVOImpl)findViewObject("SpOrderSetupVO1");
    }


    /**
     * Container's getter for SpOrderLearningCurveVO1.
     * @return SpOrderLearningCurveVO1
     */
    public SpOrderLearningCurveVOImpl getSpOrderLearningCurveVO1() {
        return (SpOrderLearningCurveVOImpl)findViewObject("SpOrderLearningCurveVO1");
    }

    /**
     * Container's getter for SpOrderLearningCurveR01Link1.
     * @return SpOrderLearningCurveR01Link1
     */
    public ViewLinkImpl getSpOrderLearningCurveR01Link1() {
        return (ViewLinkImpl)findViewLink("SpOrderLearningCurveR01Link1");
    }

    /**
     * Container's getter for PopulateOrdersVO1.
     * @return PopulateOrdersVO1
     */
    public ViewObjectImpl getPopulateOrdersVO1() {
        return (ViewObjectImpl)findViewObject("PopulateOrdersVO1");
    }
}
