package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 22 11:07:34 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpOrderSetupEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OrderSetupId {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getOrderSetupId();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setOrderSetupId((Number)value);
            }
        }
        ,
        PocId {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getPocId();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getItemId();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        OrderType {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getOrderType();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setOrderType((String)value);
            }
        }
        ,
        ProductionUnit {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getProductionUnit();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setProductionUnit((Number)value);
            }
        }
        ,
        Productivity {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getProductivity();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setProductivity((Number)value);
            }
        }
        ,
        SewingStartDate {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getSewingStartDate();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setSewingStartDate((Date)value);
            }
        }
        ,
        SewingEndDate {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getSewingEndDate();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setSewingEndDate((Date)value);
            }
        }
        ,
        PbFlag {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getPbFlag();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setPbFlag((String)value);
            }
        }
        ,
        OrgId {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        Shipdate {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getShipdate();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setShipdate((Date)value);
            }
        }
        ,
        OrderQty {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getOrderQty();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        BpoId {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getBpoId();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setBpoId((String)value);
            }
        }
        ,
        SpOrderLearningCurveEO {
            public Object get(SpOrderSetupEOImpl obj) {
                return obj.getSpOrderLearningCurveEO();
            }

            public void put(SpOrderSetupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SpOrderSetupEOImpl object);

        public abstract void put(SpOrderSetupEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ORDERSETUPID = AttributesEnum.OrderSetupId.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int PRODUCTIONUNIT = AttributesEnum.ProductionUnit.index();
    public static final int PRODUCTIVITY = AttributesEnum.Productivity.index();
    public static final int SEWINGSTARTDATE = AttributesEnum.SewingStartDate.index();
    public static final int SEWINGENDDATE = AttributesEnum.SewingEndDate.index();
    public static final int PBFLAG = AttributesEnum.PbFlag.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int SHIPDATE = AttributesEnum.Shipdate.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int SPORDERLEARNINGCURVEEO = AttributesEnum.SpOrderLearningCurveEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SpOrderSetupEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.SpOrderSetupEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for OrderSetupId, using the alias name OrderSetupId.
     * @return the OrderSetupId
     */
    public Number getOrderSetupId() {
        return (Number)getAttributeInternal(ORDERSETUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderSetupId.
     * @param value value to set the OrderSetupId
     */
    public void setOrderSetupId(Number value) {
        setAttributeInternal(ORDERSETUPID, value);
    }


    /**
     * Gets the attribute value for PocId, using the alias name PocId.
     * @return the PocId
     */
    public Number getPocId() {
        return (Number)getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocId.
     * @param value value to set the PocId
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for OrderType, using the alias name OrderType.
     * @return the OrderType
     */
    public String getOrderType() {
        return (String)getAttributeInternal(ORDERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderType.
     * @param value value to set the OrderType
     */
    public void setOrderType(String value) {
        setAttributeInternal(ORDERTYPE, value);
    }

    /**
     * Gets the attribute value for ProductionUnit, using the alias name ProductionUnit.
     * @return the ProductionUnit
     */
    public Number getProductionUnit() {
        return (Number)getAttributeInternal(PRODUCTIONUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionUnit.
     * @param value value to set the ProductionUnit
     */
    public void setProductionUnit(Number value) {
        setAttributeInternal(PRODUCTIONUNIT, value);
    }

    /**
     * Gets the attribute value for Productivity, using the alias name Productivity.
     * @return the Productivity
     */
    public Number getProductivity() {
        return (Number)getAttributeInternal(PRODUCTIVITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productivity.
     * @param value value to set the Productivity
     */
    public void setProductivity(Number value) {
        setAttributeInternal(PRODUCTIVITY, value);
    }

    /**
     * Gets the attribute value for SewingStartDate, using the alias name SewingStartDate.
     * @return the SewingStartDate
     */
    public Date getSewingStartDate() {
        return (Date)getAttributeInternal(SEWINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SewingStartDate.
     * @param value value to set the SewingStartDate
     */
    public void setSewingStartDate(Date value) {
        setAttributeInternal(SEWINGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for SewingEndDate, using the alias name SewingEndDate.
     * @return the SewingEndDate
     */
    public Date getSewingEndDate() {
        return (Date)getAttributeInternal(SEWINGENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SewingEndDate.
     * @param value value to set the SewingEndDate
     */
    public void setSewingEndDate(Date value) {
        setAttributeInternal(SEWINGENDDATE, value);
    }

    /**
     * Gets the attribute value for PbFlag, using the alias name PbFlag.
     * @return the PbFlag
     */
    public String getPbFlag() {
        return (String)getAttributeInternal(PBFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PbFlag.
     * @param value value to set the PbFlag
     */
    public void setPbFlag(String value) {
        setAttributeInternal(PBFLAG, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Shipdate, using the alias name Shipdate.
     * @return the Shipdate
     */
    public Date getShipdate() {
        return (Date)getAttributeInternal(SHIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shipdate.
     * @param value value to set the Shipdate
     */
    public void setShipdate(Date value) {
        setAttributeInternal(SHIPDATE, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }


    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public String getBpoId() {
        return (String)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(String value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSpOrderLearningCurveEO() {
        return (RowIterator)getAttributeInternal(SPORDERLEARNINGCURVEEO);
    }


    /**
     * @param orderSetupId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number orderSetupId) {
        return new Key(new Object[]{orderSetupId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String orgId = (String)sessionScope.get("orgId");
    
        super.create(attributeList);
        
         oracle.jbo.server.SequenceImpl s =
         new oracle.jbo.server.SequenceImpl("SP_ORDER_SETUP_S",  getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
         this.setOrderSetupId(sVal);
                  
        try {
        
            this.setOrgId( new Number(orgId)  );
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
             String user = (String)sessionScope.get("userId");
             
        //        System.out.println("Document No -->" + getSrNoString());
              
             if (DML_UPDATE == operation) {
                 try {
                     setLastUpdatedDate((Date)Date.getCurrentDate());
                     setLastUpdatedBy(new oracle.jbo.domain.Number(user));              
                     
                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             } else if (DML_INSERT == operation) {

                 try {
                   
                     setCreationDate((Date)Date.getCurrentDate());
                     setCreatedBy(new oracle.jbo.domain.Number(user));

                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             }
             
         
        super.doDML(operation, e);
    }
}
