package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 22 11:07:28 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpOrderLearningCurveEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OlcId {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getOlcId();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setOlcId((Number)value);
            }
        }
        ,
        OrderSetupId {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getOrderSetupId();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setOrderSetupId((Number)value);
            }
        }
        ,
        DayNo {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getDayNo();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setDayNo((Number)value);
            }
        }
        ,
        LearningPercentage {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getLearningPercentage();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setLearningPercentage((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        SpOrderSetupEO {
            public Object get(SpOrderLearningCurveEOImpl obj) {
                return obj.getSpOrderSetupEO();
            }

            public void put(SpOrderLearningCurveEOImpl obj, Object value) {
                obj.setSpOrderSetupEO((SpOrderSetupEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(SpOrderLearningCurveEOImpl object);

        public abstract void put(SpOrderLearningCurveEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OLCID = AttributesEnum.OlcId.index();
    public static final int ORDERSETUPID = AttributesEnum.OrderSetupId.index();
    public static final int DAYNO = AttributesEnum.DayNo.index();
    public static final int LEARNINGPERCENTAGE = AttributesEnum.LearningPercentage.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int SPORDERSETUPEO = AttributesEnum.SpOrderSetupEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SpOrderLearningCurveEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.SpOrderLearningCurveEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for OlcId, using the alias name OlcId.
     * @return the OlcId
     */
    public Number getOlcId() {
        return (Number)getAttributeInternal(OLCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OlcId.
     * @param value value to set the OlcId
     */
    public void setOlcId(Number value) {
        setAttributeInternal(OLCID, value);
    }

    /**
     * Gets the attribute value for OrderSetupId, using the alias name OrderSetupId.
     * @return the OrderSetupId
     */
    public Number getOrderSetupId() {
        return (Number)getAttributeInternal(ORDERSETUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderSetupId.
     * @param value value to set the OrderSetupId
     */
    public void setOrderSetupId(Number value) {
        setAttributeInternal(ORDERSETUPID, value);
    }

    /**
     * Gets the attribute value for DayNo, using the alias name DayNo.
     * @return the DayNo
     */
    public Number getDayNo() {
        return (Number)getAttributeInternal(DAYNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayNo.
     * @param value value to set the DayNo
     */
    public void setDayNo(Number value) {
        setAttributeInternal(DAYNO, value);
    }

    /**
     * Gets the attribute value for LearningPercentage, using the alias name LearningPercentage.
     * @return the LearningPercentage
     */
    public Number getLearningPercentage() {
        return (Number)getAttributeInternal(LEARNINGPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LearningPercentage.
     * @param value value to set the LearningPercentage
     */
    public void setLearningPercentage(Number value) {
        setAttributeInternal(LEARNINGPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity SpOrderSetupEOImpl.
     */
    public SpOrderSetupEOImpl getSpOrderSetupEO() {
        return (SpOrderSetupEOImpl)getAttributeInternal(SPORDERSETUPEO);
    }

    /**
     * Sets <code>value</code> as the associated entity SpOrderSetupEOImpl.
     */
    public void setSpOrderSetupEO(SpOrderSetupEOImpl value) {
        setAttributeInternal(SPORDERSETUPEO, value);
    }


    /**
     * @param olcId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number olcId) {
        return new Key(new Object[]{olcId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
                
           super.create(attributeList);
        
            oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("SP_ORDER_LEARNING_CURVE_S",  getDBTransaction());
           oracle.jbo.domain.Number sVal = s.getSequenceNumber();
            this.setOlcId(sVal);


    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
             String user = (String)sessionScope.get("userId");
             
        //        System.out.println("Document No -->" + getSrNoString());
              
             if (DML_UPDATE == operation) {
                 try {
                     setLastUpdatedDate((Date)Date.getCurrentDate());
                     setLastUpdatedBy(new oracle.jbo.domain.Number(user));              
                     
                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             } else if (DML_INSERT == operation) {

                 try {
                   
                     setCreationDate((Date)Date.getCurrentDate());
                     setCreatedBy(new oracle.jbo.domain.Number(user));

                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             }
//             
         
        super.doDML(operation, e);
    }
}
