package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 22 16:49:15 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateOrdersVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PopulateOrdersVOImpl() {
    }
}
